@startuml
left to right direction
skinparam style strictuml
skinparam packageStyle rect
skinparam backgroundcolor transparent
skinparam defaultfontname Verdana
actor "Enseignant" as T
actor "Étudiant" as S

rectangle "Système" {
  (Sauvegarder un résultat de devoir) as SRD #powderblue
  (Sauvegarder un résultat de questionnaire) as SRQ #powderblue
  (Récupérer les résultats d'un étudiant) as RRE #powderblue
  (Récupérer les résultats d'un cour) as RRC #powderblue
  (Effacer toute les notes) as EN #powderblue
  (Récupérer la liste des cours) as RLC #powderblue
  (Récupérer la liste des étudiants) as RLE #powderblue
  (Login) as L
  T -- L
  S -- L
  S -- SRD
  S -- SRQ
  T -- RRE
  T -- RRC
  T -- EN
  T -- RLC
  T -- RLE
}
@enduml

