@startuml
left to right direction
skinparam style strictuml
skinparam packageStyle rect
skinparam backgroundcolor transparent
skinparam defaultfontname Verdana
actor "Application Client" as C
rectangle "Système" {
  (Sauvegarder un résultat de devoir) as SRD #powderblue
  (Sauvegarder un résultat de questionnaire) as SRQ #powderblue
  (Récupérer les résultats d'un étudiant) as RRE #powderblue
  C -- SRD
  C -- SRQ
  C -- RRE
}
@enduml